# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Reza Mohammadi
email: rezamohammadi.edu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My personal webpage to share what I learn and what I do!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rezam1998.github.io/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  rezam1998

# Build settings
markdown: kramdown
plugins:
  - jekyll-remote-theme
remote_theme: "mmistakes/jekyll-theme-basically-basic"

